### ISSUE TITLE
take picture with a button click

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SediNetCam#10]
related to #9 and camera software

**Comment by jacobstasiewicz** [comment]
When button is pressed camera now will take a picture and upload a corresponding time and gps location to a csv file along with the name of the picture

**Comment by ebgoldstein** [comment]
@jacobstasiewicz — I'm going to reopen this issue — can you post the code you are using to take the picture to the github repository in a new `/camerasoftware` directory)? After you commit the code, feel free to close again..
