### ISSUE TITLE
grainsize pics

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SediNetCam#12]
take pictures of the reference sand that you collected as a reference pics. Store these pictures in the (`/grainsize` directory)

**Comment by jacobstasiewicz** [comment]
For the reference pictures should I use the full size image or the cropped 512x512 image

**Comment by ebgoldstein** [comment]
full size

**Comment by ebgoldstein** [comment]
loaded via https://github.com/UNCG-DAISY/SediNetCam/commit/20b955fb2100b2f0e8a6abf9c93b78f1f63ecec2

my money is on 4* or 5* being the best...
