### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SediNetCam#20]
for the RPi, components (screen, button, GPS,etc).

And perhaps instructions, so someone can build one after ordering the parts in the Bill of Materials.

**Comment by jacobstasiewicz** [comment]
Added Wiring_Diagram.png, I am going to start on setup documentation tonight

**Comment by ebgoldstein** [comment]
closed via https://github.com/UNCG-DAISY/SediNetCam/commit/cf64def18296d9bc650417202137382384e19c23

**Comment by jacobstasiewicz** [comment]
Needed finalized fritzing diagram

**Comment by jacobstasiewicz** [comment]
finished, forgot to close
