### ISSUE TITLE
pyDGS

### ISSUE THREAD

**Issue by jacobstasiewicz** [UNCG-DAISY/SediNetCam#25]
Work on running the sample images through pyDGS

**Comment by jacobstasiewicz** [comment]
After running different images through pyDGS and using different parameters for the different photos I have determined that because the sample sand is not well sorted (it is moderately sorted) pyDGS is a poor script for sediment size

**Comment by ebgoldstein** [comment]
discussion as to why PyDGS is not working for our pics: https://github.com/dbuscombe-usgs/pyDGS/issues/16

**Comment by jacobstasiewicz** [comment]
got pyDGS working fairly well. Going to work on installing it on camera now

**Comment by jacobstasiewicz** [comment]
got pyDGS working on raspberry pi 4 at home going to try and deploy it on sedinet cam tomorrow

**Comment by jacobstasiewicz** [comment]
pyDGS is successfully working on Cam
