### ISSUE TITLE
determine best distance from the bed for camera

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/SediNetCam#7]
this will be determined via back and forth with the sedinet model

**Comment by ebgoldstein** [comment]
from @jacobstasiewicz:
I took 3 pictures of a camera calibration board from 3 different distances to calculate pixel per inch. The results are as follows:
distance: 4 7/8 has a PPI of 624.38
distance: 3 1/2 in has a PPI of 858.52
distance: 2 1/2 in has a PPI of 1144.69

**Comment by jacobstasiewicz** [comment]
Ordered tripod to take precise pictures at different elevations and run through SediNet

**Comment by jacobstasiewicz** [comment]
Took 15 pictures at varying heights from 3 inches to 7 inches above the bed to run through sedinet model

**Comment by jacobstasiewicz** [comment]
Cropped all pictures to 512 x 512 for sedinet model

**Comment by jacobstasiewicz** [comment]
did calculations on lens angle to find pixels per mm

**Comment by jacobstasiewicz** [comment]
found to be 3in
